update source_version and base_version
conda-forge/omniscidb-feedstock pull request #84
Opened 2022-03-02 14:51 UTC by guilhermeleobas

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2022-03-02 14:51 UTC, guilhermeleobas commented
@conda-forge-admin, please rerender

2022-03-02 15:00 UTC, guilhermeleobas commented
@conda-forge-admin, please restart ci

2022-03-02 15:00 UTC, closed without merging

2022-03-03 08:44 UTC, pearu requested changes
We don't need the 5.10.1 specific patch file.

2022-03-03 08:44 UTC, pearu commented on recipe/meta.yaml
> +    - 0001-Fix-DBE-build.patch  # [version == "5.10.1"]
Since we don't build for 5.10.1 anymore, this patch as well as the patch file itself can be removed:
```suggestion
```