[do not merge] patch to build v6 on windows
conda-forge/omniscidb-feedstock pull request #95
Opened 2022-04-21 16:59 UTC by guilhermeleobas

2022-04-21 16:59 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-04-21 19:18 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but it appears we have a merge conflict.
Please try to merge or rebase with the base branch to resolve this conflict.

Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2022-04-21 19:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-04-28 13:07 UTC, guilhermeleobas commented
@brenocfg, if you could take a look as well.

2022-05-18 20:03 UTC, pearu approved these changes
LGTM! Thanks, @guilhermeleobas!

2022-05-18 20:06 UTC, pearu requested changes
@guilhermeleobas , please increment the build number.

2022-05-19 07:59 UTC, pearu approved these changes
LGTM!

2022-05-19 08:00 UTC, merged